# ==============================================================================
# Statistical Analysis: Doripenem BBB Penetration Study (R)
# ==============================================================================
# Based on: Margetis et al. (2011) "Penetration of Intact Blood-Brain Barrier
#           by Doripenem" — Antimicrob Agents Chemother, 55(7):3637-3638
#           https://pmc.ncbi.nlm.nih.gov/articles/PMC3122383/
#
# Analyses performed (NOT in the original paper):
#   Part A — Correlation & Multiple Linear Regression
#   Part B — Logistic Regression for Therapeutic Threshold + ROC/AUC
#
# Dataset: Synthetic (n=200), consistent with published PK profiles.
# ==============================================================================

# --- Install packages if needed ---
required_pkgs <- c("pROC", "car", "caret", "corrplot")
for (pkg in required_pkgs) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg, repos = "https://cloud.r-project.org", quiet = TRUE)
  }
}

library(pROC)
library(car)
library(caret)
library(corrplot)

# ==============================================================================
# 0. LOAD DATA
# ==============================================================================
df <- read.csv("doripenem_bbb_synthetic_data.csv", stringsAsFactors = FALSE)
df$sex_numeric <- ifelse(df$sex == "M", 1, 0)

cat("======================================================================\n")
cat("DORIPENEM BBB PENETRATION — STATISTICAL ANALYSIS (R)\n")
cat("======================================================================\n\n")
cat(sprintf("Dataset: n = %d patients\n", nrow(df)))
cat(sprintf("Therapeutic threshold met (CSF >= 0.25 ug/ml): %d/%d (%.1f%%)\n\n",
            sum(df$therapeutic_threshold_met), nrow(df),
            100 * mean(df$therapeutic_threshold_met)))

cat("--- Descriptive Statistics ---\n\n")
summary_vars <- df[, c("age_years", "weight_kg", "bmi",
                        "creatinine_clearance_ml_min", "sampling_time_min",
                        "plasma_concentration_ug_ml", "csf_concentration_ug_ml",
                        "csf_plasma_ratio")]
print(summary(summary_vars))

# ==============================================================================
# PART A: CORRELATION ANALYSIS & MULTIPLE LINEAR REGRESSION
# ==============================================================================
cat("\n\n======================================================================\n")
cat("PART A: CORRELATION ANALYSIS & MULTIPLE LINEAR REGRESSION\n")
cat("======================================================================\n")

# --- A1: Pearson Correlation Matrix ---
cat("\n--- A1: Pearson Correlation Matrix ---\n\n")
corr_vars <- c("age_years", "weight_kg", "bmi",
               "creatinine_clearance_ml_min", "sampling_time_min",
               "plasma_concentration_ug_ml", "csf_concentration_ug_ml",
               "csf_plasma_ratio")
corr_matrix <- cor(df[, corr_vars], method = "pearson")
print(round(corr_matrix, 3))

# --- A2: Spearman Correlations ---
cat("\n--- A2: Spearman Rank Correlations (CSF conc vs. covariates) ---\n\n")
spearman_vars <- c("sampling_time_min", "weight_kg", "age_years",
                   "creatinine_clearance_ml_min", "bmi",
                   "plasma_concentration_ug_ml")

for (v in spearman_vars) {
  test <- cor.test(df[[v]], df$csf_concentration_ug_ml, method = "spearman",
                   exact = FALSE)
  sig <- ifelse(test$p.value < 0.001, "***",
         ifelse(test$p.value < 0.01, "**",
         ifelse(test$p.value < 0.05, "*", "ns")))
  cat(sprintf("  CSF conc vs %35s: rho = %+.3f, p = %.4f %s\n",
              v, test$estimate, test$p.value, sig))
}

# --- A3: Multiple Linear Regression ---
cat("\n--- A3: Multiple Linear Regression ---\n")
cat("    Outcome: CSF/Plasma Ratio\n")
cat("    Predictors: age, weight, CrCl, sampling_time, sex\n\n")

ols_model <- lm(csf_plasma_ratio ~ age_years + weight_kg +
                  creatinine_clearance_ml_min + sampling_time_min +
                  sex_numeric, data = df)
print(summary(ols_model))

# Confidence intervals
cat("\n--- 95% Confidence Intervals for Coefficients ---\n\n")
print(round(confint(ols_model), 6))

# VIF for multicollinearity
cat("\n--- Variance Inflation Factors (VIF) ---\n\n")
vif_vals <- vif(ols_model)
for (i in seq_along(vif_vals)) {
  flag <- ifelse(vif_vals[i] > 5, " *** HIGH", "")
  cat(sprintf("  %35s: VIF = %.2f%s\n", names(vif_vals)[i], vif_vals[i], flag))
}

# NOTE: Figure 1 (correlation heatmap + scatter) is generated by analysis.py

# ==============================================================================
# PART B: LOGISTIC REGRESSION — THERAPEUTIC THRESHOLD
# ==============================================================================
cat("\n\n======================================================================\n")
cat("PART B: LOGISTIC REGRESSION — THERAPEUTIC THRESHOLD ACHIEVEMENT\n")
cat("======================================================================\n")
cat("\n    Outcome: CSF >= 0.25 ug/ml (binary)\n")
cat("    Predictors: age, weight, CrCl, sampling_time, sex\n\n")

# --- B1: Logistic Regression ---
logit_model <- glm(therapeutic_threshold_met ~ age_years + weight_kg +
                     creatinine_clearance_ml_min + sampling_time_min +
                     sex_numeric,
                   data = df, family = binomial(link = "logit"))
print(summary(logit_model))

# Odds ratios with 95% CI
cat("\n--- Odds Ratios with 95% CI ---\n\n")
or <- exp(coef(logit_model))
ci <- exp(confint(logit_model))
or_table <- data.frame(
  Odds_Ratio = round(or, 4),
  OR_lower_95 = round(ci[, 1], 4),
  OR_upper_95 = round(ci[, 2], 4),
  p_value = round(summary(logit_model)$coefficients[, 4], 4)
)
print(or_table)

# --- B2: Model Performance ---
pred_prob <- predict(logit_model, type = "response")
pred_class <- ifelse(pred_prob >= 0.5, 1, 0)

cat("\n--- Confusion Matrix ---\n\n")
cm <- confusionMatrix(factor(pred_class, levels = c(0, 1)),
                      factor(df$therapeutic_threshold_met, levels = c(0, 1)),
                      positive = "1")
print(cm)

# --- B3: ROC Curve & AUC ---
roc_obj <- roc(df$therapeutic_threshold_met, pred_prob, quiet = TRUE)
auc_val <- auc(roc_obj)

cat(sprintf("\n--- ROC Analysis ---\n"))
cat(sprintf("  AUC = %.3f\n", auc_val))
cat(sprintf("  95%% CI: %.3f - %.3f\n",
            ci.auc(roc_obj, quiet = TRUE)[1],
            ci.auc(roc_obj, quiet = TRUE)[3]))

# --- B4: Cross-Validation (5-fold) ---
cat("\n--- 5-Fold Cross-Validation ---\n\n")
set.seed(42)
train_ctrl <- trainControl(method = "cv", number = 5,
                           classProbs = TRUE,
                           summaryFunction = twoClassSummary)

df_cv <- df
df_cv$outcome <- factor(ifelse(df_cv$therapeutic_threshold_met == 1,
                               "Above", "Below"), levels = c("Below", "Above"))

cv_model <- train(outcome ~ age_years + weight_kg +
                    creatinine_clearance_ml_min + sampling_time_min +
                    sex_numeric,
                  data = df_cv, method = "glm", family = "binomial",
                  trControl = train_ctrl, metric = "ROC")
cat(sprintf("  CV AUC:      %.3f\n", cv_model$results$ROC))
cat(sprintf("  CV Sens:     %.3f\n", cv_model$results$Sens))
cat(sprintf("  CV Spec:     %.3f\n", cv_model$results$Spec))

# --- B5: ROC Plot (Figure 5) ---
png("figure5_logistic_regression.png", width = 1600, height = 700, res = 150)
par(mfrow = c(1, 2))

# Smoothed ROC curve — plot using original roc_obj with interpolated smoothing
# Use high-resolution interpolation on the original ROC for a smooth appearance
fpr_seq <- seq(0, 1, length.out = 500)
tpr_interp <- approx(1 - roc_obj$specificities, roc_obj$sensitivities,
                      xout = fpr_seq, method = "linear", ties = mean)$y
tpr_smooth <- stats::filter(tpr_interp, rep(1/15, 15), sides = 2)
# Fill NA edges from filter with original values
tpr_smooth[is.na(tpr_smooth)] <- tpr_interp[is.na(tpr_smooth)]
# Ensure monotonicity and endpoints
tpr_smooth <- cummax(tpr_smooth)
tpr_smooth[1] <- 0
tpr_smooth[length(tpr_smooth)] <- 1

plot(fpr_seq, tpr_smooth, type = "l", col = "darkorange", lwd = 2.5,
     xlim = c(-0.02, 1.02), ylim = c(-0.02, 1.02),
     main = "ROC Curve — Therapeutic Threshold Achievement",
     xlab = "False Positive Rate (1 - Specificity)",
     ylab = "True Positive Rate (Sensitivity)")
box(col = "black")
segments(0, 0, 1, 1, col = "gray", lty = 2, lwd = 1.5)
legend("bottomright",
       legend = c(sprintf("Logistic Regression (AUC = %.3f)", auc_val),
                  "Random (AUC = 0.5)"),
       col = c("darkorange", "gray"), lty = c(1, 2), lwd = c(2.5, 1.5),
       cex = 0.9)

# Predicted probability by sampling time
plot(df$sampling_time_min, pred_prob,
     col = ifelse(df$therapeutic_threshold_met == 1, "forestgreen", "red"),
     pch = 19, cex = 1.2,
     xlab = "Sampling Time (min post-infusion)",
     ylab = "Predicted Probability (CSF >= MIC)",
     main = "Predicted Therapeutic Achievement\nby Sampling Time")
abline(h = 0.5, col = "red", lty = 2, lwd = 2)
legend("bottomright",
       legend = c("Actually Above MIC", "Actually Below MIC", "Decision Boundary"),
       col = c("forestgreen", "red", "red"),
       pch = c(19, 19, NA), lty = c(NA, NA, 2), lwd = c(NA, NA, 2),
       cex = 0.9)

dev.off()
cat("\nSaved: figure5_logistic_regression.png\n")

# ==============================================================================
# ADDITIONAL TABLE FIGURES (R-generated)
# ==============================================================================

# --- Figure 3: Full OLS Regression Summary Table ---
ols_summary <- summary(ols_model)
ols_coefs <- ols_summary$coefficients
ols_ci <- confint(ols_model)

# Build table data
ols_tab <- data.frame(
  Variable = rownames(ols_coefs),
  Coefficient = sprintf("%.4f", ols_coefs[, "Estimate"]),
  Std_Error = sprintf("%.4f", ols_coefs[, "Std. Error"]),
  t_statistic = sprintf("%.3f", ols_coefs[, "t value"]),
  P_Value = sprintf("%.4f", ols_coefs[, "Pr(>|t|)"]),
  CI_95 = sprintf("[%.4f, %.4f]", ols_ci[, 1], ols_ci[, 2]),
  stringsAsFactors = FALSE
)

png("figure3_ols_summary.png", width = 1400, height = 500, res = 150)
par(mar = c(4, 1, 4, 1))
plot.new()

# Title
title(main = sprintf("Multiple Linear Regression — CSF/Plasma Ratio\nR² = %.3f   Adj. R² = %.3f   F = %.2f (p = %.4f)   n = %d",
                      ols_summary$r.squared, ols_summary$adj.r.squared,
                      ols_summary$fstatistic[1],
                      pf(ols_summary$fstatistic[1], ols_summary$fstatistic[2], ols_summary$fstatistic[3], lower.tail = FALSE),
                      nrow(df)),
      cex.main = 1.1, font.main = 2)

# Table content
col_names <- c("Variable", "Coefficient", "Std Error", "t-statistic", "P-Value", "95% CI")
n_rows <- nrow(ols_tab)
n_cols <- length(col_names)

# Draw table
x_positions <- seq(0.02, 0.98, length.out = n_cols + 1)
y_start <- 0.82
row_height <- 0.10

# Header
for (j in 1:n_cols) {
  rect(x_positions[j], y_start, x_positions[j + 1], y_start + row_height,
       col = "#4472c4", border = "#dddddd")
  text((x_positions[j] + x_positions[j + 1]) / 2, y_start + row_height / 2,
       col_names[j], col = "white", font = 2, cex = 0.75)
}

# Data rows
for (i in 1:n_rows) {
  y_pos <- y_start - i * row_height
  p_val <- ols_coefs[i, "Pr(>|t|)"]
  bg_col <- ifelse(p_val < 0.001, "#c6efce", ifelse(p_val < 0.05, "#fff3cd", "#f8f9fa"))
  row_data <- c(ols_tab$Variable[i], ols_tab$Coefficient[i], ols_tab$Std_Error[i],
                ols_tab$t_statistic[i], ols_tab$P_Value[i], ols_tab$CI_95[i])
  for (j in 1:n_cols) {
    rect(x_positions[j], y_pos, x_positions[j + 1], y_pos + row_height,
         col = bg_col, border = "#dddddd")
    text((x_positions[j] + x_positions[j + 1]) / 2, y_pos + row_height / 2,
         row_data[j], cex = 0.65)
  }
}

# Footnote
mtext("Dependent variable: CSF/plasma penetration ratio", side = 1, line = 1.5,
      cex = 0.7, font = 3, col = "#555555")

dev.off()
cat("Saved: figure3_ols_summary.png\n")

# NOTE: Figure 2 (p-value summary) and Figure 4 (odds ratios + forest plot)
#       are generated by analysis.py

# ==============================================================================
# SUMMARY
# ==============================================================================
cat("\n\n======================================================================\n")
cat("ANALYSIS COMPLETE\n")
cat("======================================================================\n")
cat("
Files generated (R):
  - figure3_ols_summary.png            (full OLS regression table)
  - figure5_logistic_regression.png    (ROC curve + probability plot)

Files generated by analysis.py:
  - figure1_correlation_analysis.png   (heatmap + scatter plot)
  - figure2_pvalue_summary.png         (comprehensive p-value table)
  - figure4_odds_ratios.png            (odds ratios + forest plot)

Analyses performed:
  Part A: Pearson & Spearman correlations, Multiple Linear Regression (OLS)
          with VIF multicollinearity diagnostics
  Part B: Logistic Regression with odds ratios, ROC/AUC, confusion matrix,
          5-fold cross-validation
\n")
