# ==============================================================================
# Statistical Analysis: Doripenem BBB Penetration Study (R)
# ==============================================================================
# Based on: Margetis et al. (2011) "Penetration of Intact Blood-Brain Barrier
#           by Doripenem" — Antimicrob Agents Chemother, 55(7):3637-3638
#           https://pmc.ncbi.nlm.nih.gov/articles/PMC3122383/
#
# Analyses performed (NOT in the original paper):
#   Part A — Correlation & Multiple Linear Regression
#   Part B — Logistic Regression for Therapeutic Threshold + ROC/AUC
#
# Variables analysed: age, weight, creatinine clearance, sampling time,
#                     CSF/plasma ratio.
# Dataset: Synthetic (n=200), consistent with published PK profiles.
# ==============================================================================

# --- Install packages if needed ---
required_pkgs <- c("pROC")
for (pkg in required_pkgs) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg, repos = "https://cloud.r-project.org", quiet = TRUE)
  }
}

library(pROC)

# ==============================================================================
# 0. LOAD DATA
# ==============================================================================
df <- read.csv("doripenem_bbb_synthetic_data.csv", stringsAsFactors = FALSE)

cat("======================================================================\n")
cat("DORIPENEM BBB PENETRATION — STATISTICAL ANALYSIS (R)\n")
cat("======================================================================\n\n")
cat(sprintf("Dataset: n = %d patients\n", nrow(df)))
cat(sprintf("Therapeutic threshold met (CSF >= 0.25 ug/ml): %d/%d (%.1f%%)\n\n",
            sum(df$therapeutic_threshold_met), nrow(df),
            100 * mean(df$therapeutic_threshold_met)))

# ==============================================================================
# DEFINE ANALYSIS VARIABLES
# ==============================================================================
# Display labels for clean figure output
var_labels <- c(
  "age_years" = "Age (yrs)",
  "weight_kg" = "Weight (kg)",
  "creatinine_clearance_ml_min" = "CrCl (mL/min)",
  "sampling_time_min" = "Sampling Time (min)",
  "csf_plasma_ratio" = "CSF/Plasma Ratio",
  "(Intercept)" = "Intercept"
)

# Five core variables used consistently across all analyses
analysis_vars <- c("age_years", "weight_kg", "creatinine_clearance_ml_min",
                   "sampling_time_min", "csf_plasma_ratio")
# Predictors for regression models (all except the outcome)
predictor_vars <- c("age_years", "weight_kg", "creatinine_clearance_ml_min",
                    "sampling_time_min")

# ==============================================================================
# PART A: CORRELATION ANALYSIS & MULTIPLE LINEAR REGRESSION
# ==============================================================================
cat("\n======================================================================\n")
cat("PART A: CORRELATION ANALYSIS & MULTIPLE LINEAR REGRESSION\n")
cat("======================================================================\n")

# --- A1: Pearson Correlation Matrix ---
cat("\n--- A1: Pearson Correlation Matrix ---\n\n")
corr_matrix <- cor(df[, analysis_vars], method = "pearson")
print(round(corr_matrix, 3))

# --- A2: Spearman Correlations ---
cat("\n--- A2: Spearman Rank Correlations (CSF/plasma ratio vs. covariates) ---\n\n")
for (v in predictor_vars) {
  test <- cor.test(df[[v]], df$csf_plasma_ratio, method = "spearman", exact = FALSE)
  sig <- ifelse(test$p.value < 0.001, "***",
         ifelse(test$p.value < 0.01, "**",
         ifelse(test$p.value < 0.05, "*", "ns")))
  cat(sprintf("  CSF/plasma ratio vs %35s: rho = %+.3f, p = %.4f %s\n",
              v, test$estimate, test$p.value, sig))
}

# --- A3: Multiple Linear Regression ---
cat("\n--- A3: Multiple Linear Regression ---\n")
cat("    Outcome: CSF/Plasma Ratio\n")
cat("    Predictors: age, weight, CrCl, sampling_time\n\n")

ols_model <- lm(csf_plasma_ratio ~ age_years + weight_kg +
                  creatinine_clearance_ml_min + sampling_time_min, data = df)
print(summary(ols_model))

# NOTE: Figure 1 (correlation heatmap + scatter) is generated by analysis.py

# ==============================================================================
# PART B: LOGISTIC REGRESSION — THERAPEUTIC THRESHOLD
# ==============================================================================
cat("\n\n======================================================================\n")
cat("PART B: LOGISTIC REGRESSION — THERAPEUTIC THRESHOLD ACHIEVEMENT\n")
cat("======================================================================\n")
cat("\n    Outcome: CSF >= 0.25 ug/ml (binary)\n")
cat("    Predictors: age, weight, CrCl, sampling_time\n\n")

# --- B1: Logistic Regression ---
logit_model <- glm(therapeutic_threshold_met ~ age_years + weight_kg +
                     creatinine_clearance_ml_min + sampling_time_min,
                   data = df, family = binomial(link = "logit"))
print(summary(logit_model))

# Odds ratios with 95% CI
cat("\n--- Odds Ratios with 95% CI ---\n\n")
or <- exp(coef(logit_model))
ci <- exp(confint(logit_model))
or_table <- data.frame(
  Odds_Ratio = round(or, 4),
  OR_lower_95 = round(ci[, 1], 4),
  OR_upper_95 = round(ci[, 2], 4),
  p_value = round(summary(logit_model)$coefficients[, 4], 4)
)
print(or_table)

# --- B2: ROC Curve & AUC ---
pred_prob <- predict(logit_model, type = "response")
roc_obj <- roc(df$therapeutic_threshold_met, pred_prob, quiet = TRUE)
auc_val <- auc(roc_obj)

cat(sprintf("\n--- ROC Analysis ---\n"))
cat(sprintf("  AUC = %.3f\n", auc_val))

# --- Figure 5: ROC Plot ---
png("figure5_logistic_regression.png", width = 1600, height = 720, res = 150)
par(mfrow = c(1, 2), oma = c(1.5, 0, 0, 0))

# Smoothed ROC curve using binormal method, plotted manually
roc_smooth <- smooth(roc_obj, method = "binormal")
smooth_fpr <- 1 - roc_smooth$specificities
smooth_tpr <- roc_smooth$sensitivities
ord <- order(smooth_fpr)

plot(NA, xlim = c(-0.02, 1.02), ylim = c(-0.02, 1.02),
     main = "ROC Curve — Therapeutic Threshold Achievement",
     xlab = "False Positive Rate (1 - Specificity)",
     ylab = "True Positive Rate (Sensitivity)")
segments(0, 0, 1, 1, col = "gray", lty = 2, lwd = 1.5)
lines(smooth_fpr[ord], smooth_tpr[ord], col = "darkorange", lwd = 2.5)
legend("bottomright",
       legend = c(sprintf("Logistic Regression (AUC = %.3f)", auc_val),
                  "Random (AUC = 0.5)"),
       col = c("darkorange", "gray"), lty = c(1, 2), lwd = c(2.5, 1.5),
       cex = 0.9)

# Predicted probability by sampling time
plot(df$sampling_time_min, pred_prob,
     col = ifelse(df$therapeutic_threshold_met == 1, "forestgreen", "red"),
     pch = 19, cex = 1.2,
     xlab = "Sampling Time (min post-infusion)",
     ylab = "Predicted Probability (CSF >= MIC)",
     main = "Predicted Therapeutic Achievement\nby Sampling Time")
abline(h = 0.5, col = "red", lty = 2, lwd = 2)
legend("bottomright",
       legend = c("Actually Above MIC", "Actually Below MIC", "Decision Boundary"),
       col = c("forestgreen", "red", "red"),
       pch = c(19, 19, NA), lty = c(NA, NA, 2), lwd = c(NA, NA, 2),
       cex = 0.9)

mtext("Model includes all 4 predictors (Age, Weight, CrCl, Sampling Time); Sampling Time plotted as the dominant predictor (p < 0.001).",
      side = 1, line = 0.5, cex = 0.65, font = 3, col = "#555555", outer = TRUE)

dev.off()
cat("\nSaved: figure5_logistic_regression.png\n")

# ==============================================================================
# Figure 3: Full OLS Regression Summary Table
# ==============================================================================
ols_summary <- summary(ols_model)
ols_coefs <- ols_summary$coefficients
ols_ci <- confint(ols_model)

ols_tab <- data.frame(
  Variable = ifelse(rownames(ols_coefs) %in% names(var_labels),
                    var_labels[rownames(ols_coefs)], rownames(ols_coefs)),
  Coefficient = sprintf("%.4f", ols_coefs[, "Estimate"]),
  Std_Error = sprintf("%.4f", ols_coefs[, "Std. Error"]),
  t_statistic = sprintf("%.3f", ols_coefs[, "t value"]),
  P_Value = sprintf("%.4f", ols_coefs[, "Pr(>|t|)"]),
  CI_95 = sprintf("[%.4f, %.4f]", ols_ci[, 1], ols_ci[, 2]),
  stringsAsFactors = FALSE
)

png("figure3_ols_summary.png", width = 1400, height = 550, res = 150)
par(mar = c(4, 1, 4, 1))
plot.new()

title(main = sprintf("Multiple Linear Regression — CSF/Plasma Ratio\nR² = %.3f   Adj. R² = %.3f   F = %.2f (p = %.4f)   n = %d",
                      ols_summary$r.squared, ols_summary$adj.r.squared,
                      ols_summary$fstatistic[1],
                      pf(ols_summary$fstatistic[1], ols_summary$fstatistic[2], ols_summary$fstatistic[3], lower.tail = FALSE),
                      nrow(df)),
      cex.main = 1.1, font.main = 2)

col_names <- c("Variable", "Coefficient", "Std Error", "t-statistic", "P-Value", "95% CI")
n_rows <- nrow(ols_tab)
n_cols <- length(col_names)

x_positions <- seq(0.02, 0.98, length.out = n_cols + 1)
y_start <- 0.82
row_height <- 0.12

# Header
for (j in 1:n_cols) {
  rect(x_positions[j], y_start, x_positions[j + 1], y_start + row_height,
       col = "#4472c4", border = "#dddddd")
  text((x_positions[j] + x_positions[j + 1]) / 2, y_start + row_height / 2,
       col_names[j], col = "white", font = 2, cex = 0.75)
}

# Data rows
for (i in 1:n_rows) {
  y_pos <- y_start - i * row_height
  p_val <- ols_coefs[i, "Pr(>|t|)"]
  bg_col <- ifelse(p_val < 0.001, "#c6efce", ifelse(p_val < 0.05, "#fff3cd", "#f8f9fa"))
  row_data <- c(ols_tab$Variable[i], ols_tab$Coefficient[i], ols_tab$Std_Error[i],
                ols_tab$t_statistic[i], ols_tab$P_Value[i], ols_tab$CI_95[i])
  for (j in 1:n_cols) {
    rect(x_positions[j], y_pos, x_positions[j + 1], y_pos + row_height,
         col = bg_col, border = "#dddddd")
    text((x_positions[j] + x_positions[j + 1]) / 2, y_pos + row_height / 2,
         row_data[j], cex = 0.65)
  }
}

mtext("Dependent variable: CSF/plasma ratio", side = 1, line = 1.5,
      cex = 0.7, font = 3, col = "#555555")

dev.off()
cat("Saved: figure3_ols_summary.png\n")

# NOTE: Figure 2 (p-value summary) and Figure 4 (odds ratios + forest plot)
#       are generated by analysis.py

# ==============================================================================
# SUMMARY
# ==============================================================================
cat("\n\n======================================================================\n")
cat("ANALYSIS COMPLETE\n")
cat("======================================================================\n")
cat("
Files generated (R):
  - figure3_ols_summary.png            (full OLS regression table)
  - figure5_logistic_regression.png    (ROC curve + probability plot)

Files generated by analysis.py:
  - figure1_correlation_analysis.png   (heatmap + scatter plot)
  - figure2_pvalue_summary.png         (comprehensive p-value table)
  - figure4_odds_ratios.png            (odds ratios + forest plot)

Analyses performed:
  Part A: Pearson & Spearman correlations, Multiple Linear Regression (OLS)
  Part B: Logistic Regression with odds ratios, ROC/AUC
\n")
